# Punto 3 Recuperación ranqueada y vectorización de documentos (RRDV)
## Integrantes
* Juan Esteban Arboleda
* Luccas Rojas

### 1. Preprocesamiento
Lo primero que se llevara a cabo para poder hacer la recuperación ranqueada es la tokenizacion de los documentos y generacion del vocabulario. Ademas es importante tener en cuenta que el vocabulario debe estar ordenado, no debe contener stop-words, debe estar stemizado y normalizado

* A continucion se cargan los documentos y los queries en una estructura de datos, se debe cambiar DOCUMENTS_PATH y QUERIES_PATH por la ruta donde se encuentran los documentos y los queries respectivamente
* El archivo de salida es guardado en RRDV_RESULTS_FILE_PATH con el formato exigido

In [112]:
import os
import pandas as pd
import numpy as np
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import math
import time

# Rutas a definir segun la ubicacion de los archivos
DOCUMENTS_PATH = '../data/docs-raw-texts'
QUERIES_PATH = '../data/queries-raw-texts'
RRDV_RESULTS_FILE_PATH = "../data/RRDV-consultas_resultados"

def load_documents(folder_path: str) -> pd.DataFrame:
    """
    Returns a Pandas DataFrame where each row represents a document in folder_path.
    The DataFrame will have as many rows as there are documents in folder_path

        Parameters
        ----------
            folder_path: str
                The path to the folder that contains the documents to load
    
        Returns
        --------
            documents: pd.DataFrame
                Pandas DataFrame with two columns: "filename" and "body"
    """
    documents = []
    index = []
    id = 1
    columns = ['filename', 'body']
    for filename in os.listdir(folder_path):
        text = pd.read_xml(os.path.join(folder_path, filename))['raw'].tolist()[1]
        filtered_text = text.replace('\n', ' ').replace('\xa0', ' ')
        document = [filename, filtered_text]
        documents.append(document)
        index.append(id)
        id += 1

    return pd.DataFrame(documents, index, columns)

documents = load_documents(DOCUMENTS_PATH)
queries = load_documents(QUERIES_PATH)

documents

filename                                               body
1    wes2015.d001.naf  William Beaumont and the Human Digestion.  Wil...
2    wes2015.d002.naf  Selma Lagerlöf and the wonderful Adventures of...
3    wes2015.d003.naf  Ferdinand de Lesseps and the Suez Canal.  Ferd...
4    wes2015.d004.naf  Walt Disney’s ‘Steamboat Willie’ and the Rise ...
5    wes2015.d005.naf  Eugene Wigner and the Structure of the Atomic ...
..                ...                                                ...
327  wes2015.d327.naf  James Parkinson and Parkinson’s Disease.  Wood...
328  wes2015.d328.naf  Juan de la Cierva and the Autogiro.  Demonstra...
329  wes2015.d329.naf  Squire Whipple – The Father of the Iron Bridge...
330  wes2015.d330.naf  William Playfair and the Beginnings of Infogra...
331  wes2015.d331.naf  Juan Bautista de Anza and the Route to San Fra...

[331 rows x 2 columns]

Primero que todo tokenizamos el texto, para esto utilizamos el word tokenize de la libreria NLTK

In [113]:
nltk.download('punkt')
nltk.download('stopwords')

documents['tokens'] = documents['body'].apply(word_tokenize)
queries['tokens'] = queries['body'].apply(word_tokenize)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\luccas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\luccas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Removemos todos los signos de puntuacion, contracciones del ingles y dejamos el texto todo en minusculas (normalizar) 

In [114]:
def remove_punctuation(token_list):
    return [token.lower() for token in token_list if (token not in string.punctuation and (len(token)>1 or token.isnumeric()))]

documents['tokens']=documents['tokens'].apply(lambda x: remove_punctuation(x))
queries['tokens']=queries['tokens'].apply(lambda x: remove_punctuation(x))

Luego de tokenizar, dejar todo en minusculas, quitaremos las stop words para que reduzcan el vocabulario y no afecten el resultado final. Para esto usaremos la libreria nltk y su metodo stopwords.words('english').

In [115]:
stop_words = set(stopwords.words('english'))

#TODO no se si normalizar cuente como poner todo en minusculas
def remove_stop_words(token_list):
    return [token for token in token_list if token not in stop_words]

documents['tokens']=documents['tokens'].apply(lambda x: remove_stop_words(x))
queries['tokens']=queries['tokens'].apply(lambda x: remove_stop_words(x))

Luego de eliminar las stop words se hace stemming a las palabras restantes.

In [116]:
stemmer = PorterStemmer()
def stemming(token_list):
    return [stemmer.stem(token) for token in token_list]

documents['tokens']=documents['tokens'].apply(lambda x: stemming(x))
queries['tokens']=queries['tokens'].apply(lambda x: stemming(x))

En este punto el texto de cada documento y query esta en un formato mas facil de procesar, por lo que se procede a realizar la representacion vectorial de los documentos y queries.

## 2. Representación de los datos

A continuación se hace la implementación para transformar el anterior dataframe en una estructura de bag of word para asi tener la frecuencia de cada palabra en cada documento y query.

Primero definimos el vocabulario como todos los tokens diferentes que se encuentran en los documentos y queries.

In [117]:
def extract_vocabulary(documents):
    vocabulary = set()
    for tokens in documents['tokens']:
        vocabulary.update(tokens)
    return vocabulary
vocabulary = extract_vocabulary(documents)
sorted_vocabulary = sorted(vocabulary)
bag_of_words_index = {word: index for index, word in enumerate(sorted_vocabulary)}

Luego creamos la función que nos permite pasar del dataframe de documentos a un bag of words donde cada fila es un documento y cada columna es una palabra del vocabulario, y el valor de cada celda es la frecuencia de esa palabra en ese documento.

In [118]:
def create_bow(documents: pd.DataFrame) -> np.array:
    """
    Creates the inverted index for a document set.

    Params
    ------
        documents: pd.DataFrame
            A Pandas DataFrame that represents the document set. The
            DataFrame should have the following columns: "filename", "body".
            DataFrame's index should correspond to the document id
        
    Returns
    -------
        bow: numpy matrix
            A numpy matrix that represents the tf-idf matrix, each column represents a document vector.
            Each row represents a term in the vocabulary.
            Each value represents the frequency of the term in the document.
    """
    bow = [[0 for i in range(len(documents)+1)] for j in range(len(vocabulary))]
    bow = np.array(bow)
    print(bow)
    for id, document in documents.iterrows():
        for token in document['tokens']:
            bow[bag_of_words_index[token]][id] += 1
    
    return bow

bow = create_bow(documents)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


El siguente paso es crear la matriz tf-idf, que contendrá los valores td-idf para cada token-documento

In [119]:
def create_tf_idf_matrix(bow: np.array) -> np.array:
    """
    Creates the tf-idf matrix

    Params
    ------
        bow: numpy matrix
            A numpy matrix that contains the bag of word for each document.
        
    Returns
    -------
        tf_idf_matrix: numpy matrix
            A numpy matrix that represents the tf-idf matrix, each column represents a document vector.
            Each row represents a term in the vocabulary.
            Each value represents the tf-idf value of the term in the document.
    """
    tf_idf_matrix = np.zeros((len(vocabulary),len(documents)+1))
    documental_frecuency = np.count_nonzero(bow, axis=1)
    total_documents = float(len(bow[0])-1)
    for i in range(len(bow)):
        df = float(documental_frecuency[i])
        for j in range(len(bow[i])):
            tf = float(bow[i][j])
            tf_idf_matrix[i][j] = math.log10(1+tf) * math.log10(total_documents/df)
    return tf_idf_matrix

tf_idf_matrix = create_tf_idf_matrix(bow)

## 3. Modelamiento

A continuación se presenta la implementación del modelo de recuperación ranqueada con el método de similitud coseno. Para esto se crea una función que recibe como parámetros 2 vectores y calcula la similitud coseno entre ellos.

In [120]:
def cosine_distance(vector1: np.array,vector2:np.array) -> float:
    """
    Calculates the cosine distance between two vectors
    Params 
    ------
        vector1: numpy array
            A numpy array that represents a vector
        vector2: numpy array
            A numpy array that represents a vector
    Returns
    -------
        cosine_distance: float  
            A float that represents the cosine distance between vector1 and vector2
    """
    if np.count_nonzero(vector1) == 0 or np.count_nonzero(vector2) == 0:
        return 0
    cos_distance = np.dot(vector1, vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2))
    return cos_distance

Posteriormente creamos una función que convierte un query en un vector tf-idf con la misma estructura que los documentos, esto para poder ser operado por la similitud coseno.

In [121]:
def query_to_tf_idf(query:list,documents_tf_idf:np.array)->np.array:
    """
    Returns the tf-idf vector for the query
    Params
    ------
        query: string
            An array of tokens that represents the query
        documents_tf_idf: numpy matrix
            A numpy matrix that represents the tf-idf matrix, each column represents a document vector.
            Each row represents a term in the vocabulary.
            Each value represents the tf-idf value of the term in the document.
    Returns
    -------
        query_tf_idf: numpy array
            A numpy array that represents the tf-idf vector for the query
    """
    query_tf_idf = np.zeros(len(documents_tf_idf))
    documental_frecuency = np.count_nonzero(documents_tf_idf, axis=1)
    total_documents = float(len(documents_tf_idf[0])-1)
    for token in query:
        if token in bag_of_words_index:
            query_tf_idf[bag_of_words_index[token]] += 1
    for i in range(len(query_tf_idf)):
        value = math.log10(1+query_tf_idf[i]) * math.log10(total_documents/documental_frecuency[i])
        query_tf_idf[i] = value

    return query_tf_idf

A continuación se presenta el algoritmo de rrdv, que consiste en calcular la similitud coseno entre el query y cada uno de los documentos, y luego ordenarlos de mayor a menor según la similitud coseno. Los documentos con similitud coseno igual a 0 no se tienen en cuenta.

In [122]:
def rrdv(query:list,documents_tf_idf:np.array) -> list:
    """
    Returns the ordered list of documents according to cosine distance between the query and the documents
    Params
    ------
        query: string
            An array of tokens that represents the query
        documents_tf_idf: numpy matrix
            A numpy matrix that represents the tf-idf matrix, each column represents a document vector.
            Each row represents a term in the vocabulary.
            Each value represents the tf-idf value of the term in the document.
    Returns
    -------
        documents_cosine_distance: list of dictionaries that contain the document id and the cosine distance
    """
    query_tf_idf = query_to_tf_idf(query,documents_tf_idf)
    documents_cosine_distance = []
    for i in range(1,len(documents_tf_idf[0])):
        document_tf_idf = documents_tf_idf[:,i]
        cos_distance = cosine_distance(query_tf_idf,document_tf_idf)
        if cos_distance > 0:
            documents_cosine_distance.append({'id':i,'cosine_distance':cos_distance})
    documents_cosine_distance.sort(key=lambda x: x['cosine_distance'],reverse=True)
    return documents_cosine_distance

# 4. Evaluación
A continuación son procesados todos los queries por el algoritmo y su resultado es guardado en un archivo de texto con el formato exigido.

In [124]:
# Clear output file contents
open(RRDV_RESULTS_FILE_PATH, "w").close()

# Loop through queries
for i, query in queries.iterrows():
    # Open output file
    file = open(RRDV_RESULTS_FILE_PATH, "a")

    query_str = query['filename'].replace('.naf', '').replace('wes2015.', '')
    file.write(query_str + " ")

    res = rrdv(query['tokens'], tf_idf_matrix)

    # Write output file
    counter=0
    for doc in res:
        docId = doc['id']
        cosine = doc['cosine_distance']
        if docId < 10:
            doc_str = "d00" + str(docId)
        elif docId < 100:
            doc_str = "d0" + str(docId)
        else:
            doc_str = "d" + str(docId)
        file.write(f'{doc_str}:{cosine}')
        if counter < len(res) - 1:
            file.write(",")
        counter+=1
    if query_str != "q46":
        file.write("\n")
file.close()